SELECT NUM,
       (CASE WHEN REFRIGERATED_FLAG = 1 THEN 'Refrigerated' ELSE 'Non-refrigerated' END) as TYPE,
       CONTAINER_POSITION_X, CONTAINER_POSITION_Y, CONTAINER_POSITION_Z,
       PAYLOAD
FROM CONTAINER INNER JOIN CONTAINER_CARGOMANIFEST ON CONTAINER.NUM = CONTAINER_CARGOMANIFEST.CONTAINER_NUM
WHERE CARGO_MANIFEST_ID IN
      (SELECT ID
      FROM CARGOMANIFEST
      WHERE SHIP_MMSI = 100000001
        AND CARGOMANIFEST.STORAGE_IDENTIFICATION = 2
        AND LOADING_FLAG = 1
        AND FINISHING_DATE_TIME IS NULL);