--DROP DIMENSION TimeDimension;
DROP DIMENSION PortOriginDimension;

/*CREATE DIMENSION TimeDimension
    LEVEL year IS (SELECT UNIQUE EXTRACT(YEAR FROM FINISHING_DATE_TIME) FROM CARGOMANIFEST_PARTIAL AS YEAR) SKIP WHEN NULL
    LEVEL month IS (SELECT UNIQUE EXTRACT(MONTH FROM FINISHING_DATE_TIME) FROM CARGOMANIFEST_PARTIAL AS MONTH) SKIP WHEN NULL
HIERARCHY TimeRollUp (
    month CHILD OF
    year);*/

CREATE DIMENSION PortOriginDimension
    LEVEL continent IS (COUNTRY.continent)
    LEVEL country IS (COUNTRY.country)
    LEVEL port IS (STORAGE.identification)
HIERARCHY PortRollUp (
    port CHILD OF
    country CHILD OF
    continent
JOIN KEY (STORAGE.country_name) REFERENCES country);
