CREATE OR REPLACE VIEW "StorageInfo" AS
SELECT CONTAINER.NUM, CARGOMANIFEST_PARTIAL.STORAGE_IDENTIFICATION, CONTAINER.MAX_VOLUME, STORAGE.MAX_VOLUME AS Capacity
FROM CONTAINER
INNER JOIN CONTAINER_CARGOMANIFEST ON CONTAINER_CARGOMANIFEST.CONTAINER_NUM = CONTAINER.NUM
INNER JOIN CARGOMANIFEST_PARTIAL ON CONTAINER_CARGOMANIFEST.PARTIAL_CARGO_MANIFEST_ID = CARGOMANIFEST_PARTIAL.ID
INNER JOIN STORAGE ON STORAGE.IDENTIFICATION = CARGOMANIFEST_PARTIAL.STORAGE_IDENTIFICATION
WHERE CARGOMANIFEST_PARTIAL.FINISHING_DATE_TIME IS NOT NULL AND LOADING_FLAG = 0 

-- Call Function to obtain Occupancy Rate of all Warehouses --

select STORAGE_IDENTIFICATION, sum(MAX_VOLUME), sum(MAX_VOLUME)/capacity
from "StorageInfo"
Where storage_identification > 0
group by STORAGE_IDENTIFICATION, capacity