CREATE OR REPLACE VIEW "Storage_Container" AS
SELECT * FROM(
       SELECT CONTAINER.NUM C1,
           --id of storage where container is located
           CARGOMANIFEST_PARTIAL.STORAGE_IDENTIFICATION
        FROM CONTAINER
        INNER JOIN CONTAINER_CARGOMANIFEST ON CONTAINER_CARGOMANIFEST.CONTAINER_NUM = CONTAINER.NUM
        INNER JOIN CARGOMANIFEST_PARTIAL ON CONTAINER_CARGOMANIFEST.PARTIAL_CARGO_MANIFEST_ID = CARGOMANIFEST_PARTIAL.ID
        WHERE CARGOMANIFEST_PARTIAL.FINISHING_DATE_TIME IS NOT NULL AND LOADING_FLAG = 0
        --get most recent cargo manifest
        AND CARGOMANIFEST_PARTIAL.FINISHING_DATE_TIME = (SELECT MAX(CARGOMANIFEST_PARTIAL.FINISHING_DATE_TIME)
                                                FROM CARGOMANIFEST_PARTIAL INNER JOIN CONTAINER_CARGOMANIFEST ON CONTAINER_CARGOMANIFEST.CONTAINER_NUM = CONTAINER.NUM
                                                WHERE CONTAINER_NUM = 1))
                                                WITH READ ONLY;